<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>TradingAnarchy.MultiMiner.Backends</AssemblyName>
    <RootNamespace>TradingAnarchy.MultiMiner.Backends</RootNamespace>
    <Description>Mining backend abstractions and implementations for Trading Anarchy Multi Miner</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingAnarchy.MultiMiner.Core\TradingAnarchy.MultiMiner.Core.csproj" />
  </ItemGroup>

</Project>